/// The abstract syntax tree for terms in the **untyped lambda calculus** (λ-calculus).
///
/// This enumeration is the canonical representation of λ-terms used throughout Axiom for
/// parsing, normalization, substitution, and proof-oriented transformations. Every
/// well-formed λ-term is built inductively from exactly three formation rules—there are
/// no constants, types, or primitive operators at this layer.
///
/// ## Grammar
///
/// Terms are generated by the following BNF, where ``Term`` is the start symbol:
///
/// ```
/// t, u ::= x                    (variable)
///        | λx. t                (abstraction)
///        | t u                  (application)
/// ```
///
/// In standard notation, ``variable("x")`` denotes *x*, ``abstraction(param:body:)``
/// denotes *λx. t*, and ``application(function:argument:)`` denotes *(t₁ t₂)*—the
/// application of *t₁* to *t₂*, with association to the left in concrete syntax.
///
/// ## Inductive structure
///
/// Because abstractions embed subterms in their bodies, ``Term`` is declared `indirect`
/// so that recursive occurrences are stored by reference, keeping value semantics
/// practical for deep or shared ASTs.
public indirect enum Term {

    /// A **variable** (also called an *atom* or *identifier*).
    ///
    /// Variables are the atomic leaves of the λ-calculus. They stand for formal
    /// parameters, bound names, or free names depending on their binding context in
    /// an enclosing term.
    ///
    /// - Mathematical form: *x* (where *x* ranges over a countably infinite set of
    ///   names).
    /// - Example: the term *x* is represented as ``variable("x")``.
    case variable(String)

    /// A **lambda abstraction**—an anonymous function with a single formal parameter.
    ///
    /// An abstraction binds its parameter name in the body, extending the local binding
    /// environment. It is the sole introduction form for functions in the untyped
    /// λ-calculus; there is no separate arrow type or multi-argument syntax at this AST
    /// level (currying is expressed via nested abstractions).
    ///
    /// - Mathematical form: *λx. t* (read “lambda *x* dot *t*”), where *x* is bound in *t*.
    /// - Example: the identity function *λx. x* is
    ///   ``abstraction(param: "x", body: .variable("x"))``.
    case abstraction(param: String, body: Term)

    /// **Function application**—the elimination form for λ-terms.
    ///
    /// Application combines a function term and an argument term. In the untyped
    /// setting, any term may appear in either position; semantics (e.g. β-reduction)
    /// are defined by the outermost constructor after substitution and renaming.
    ///
    /// - Mathematical form: *(t₁ t₂)*—apply *t₁* to *t₂*. By convention, application
    ///   associates to the left: *t₁ t₂ t₃* means *((t₁ t₂) t₃)*.
    /// - Example: applying the identity to *y*, written *(λx. x) y*, is
    ///   ``application(
    ///     function: .abstraction(param: "x", body: .variable("x")),
    ///     argument: .variable("y")
    ///   )``.
    case application(function: Term, argument: Term)
}
