/// The abstract syntax tree for terms in the **simply typed lambda calculus** (STLC).
///
/// This enumeration is the canonical representation of λ-terms used throughout Axiom for
/// parsing, type checking, normalization, substitution, and proof-oriented transformations.
/// Every well-formed term is built from variables, typed abstractions, and applications.
///
/// ## Grammar
///
/// Terms are generated by the following BNF, where ``Term`` is the start symbol:
///
/// ```
/// t, u ::= x                         (variable)
///        | λx:τ. t                   (typed abstraction)
///        | t u                       (application)
/// ```
///
/// In standard notation, ``variable("x")`` denotes *x*,
/// ``abstraction(param:type:body:)`` denotes *λx:τ. t*, and
/// ``application(function:argument:)`` denotes *(t₁ t₂)*.
///
/// ## Inductive structure
///
/// Because abstractions embed subterms in their bodies, ``Term`` is declared `indirect`
/// so that recursive occurrences are stored by reference, keeping value semantics
/// practical for deep or shared ASTs.
public indirect enum Term: Equatable {

    /// A **variable** (also called an *atom* or *identifier*).
    ///
    /// Variables are the atomic leaves of the λ-calculus. They stand for formal
    /// parameters, bound names, or free names depending on their binding context in
    /// an enclosing term. Type checking assigns each variable a type from context.
    ///
    /// - Mathematical form: *x*.
    /// - Example: ``variable("x")``.
    case variable(String)

    /// A **typed lambda abstraction**—an anonymous function with annotated parameter type.
    ///
    /// The parameter is bound in the body with type ``type``; this annotation is the
    /// introduction form for functions in STLC and is preserved under substitution and
    /// β-reduction (only the body is transformed).
    ///
    /// - Mathematical form: *λx:τ. t*.
    /// - Example: the typed identity *λx:τ. x* is
    ///   ``abstraction(param: "x", type: τ, body: .variable("x"))``.
    case abstraction(param: String, type: Type, body: Term)

    /// **Function application**—the elimination form for λ-terms.
    ///
    /// Application combines a function term and an argument term. In STLC, typing rules
    /// require the function to have an arrow type matching the argument; β-reduction
    /// contracts redexes of the form *(λx:τ. t) u*.
    ///
    /// - Mathematical form: *(t₁ t₂)*.
    /// - Example: *(λx:τ. x) y* is
    ///   ``application(
    ///     function: .abstraction(param: "x", type: τ, body: .variable("x")),
    ///     argument: .variable("y")
    ///   )``.
    case application(function: Term, argument: Term)
}

// MARK: - Free variables and capture-avoiding substitution

extension Term {

    /// The set of **free variables** occurring in this term.
    ///
    /// A variable *x* is *free* in a term when it is not bound by an enclosing abstraction
    /// with parameter *x*. Type annotations on binders do not contribute to *FV*.
    ///
    /// - Variable *x*: *FV(x) = { x }*.
    /// - Abstraction *λy:τ. t*: *FV(λy:τ. t) = FV(t) \\ { y }*.
    /// - Application *(t₁ t₂)*: *FV(t₁ t₂) = FV(t₁) ∪ FV(t₂)*.
    public var freeVariables: Set<String> {
        switch self {
        case .variable(let name):
            return [name]
        case .abstraction(let param, _, let body):
            return body.freeVariables.subtracting([param])
        case .application(let function, let argument):
            return function.freeVariables.union(argument.freeVariables)
        }
    }

    /// **Capture-avoiding substitution**: the term *[name := replacement]*.
    ///
    /// Replaces every *free* occurrence of ``name`` in `self` with ``replacement``,
    /// leaving bound variables and their **type annotations** intact, performing
    /// **α-conversion** when a binder would otherwise capture a variable free in
    /// ``replacement``.
    ///
    /// - Parameters:
    ///   - name: The identifier *x* whose free occurrences are replaced.
    ///   - replacement: The term *s* substituted for those occurrences.
    /// - Returns: A term with capture-safe replacement applied; binder types unchanged.
    public func substituting(name: String, with replacement: Term) -> Term {
        switch self {
        case .variable(let variableName):
            if variableName == name {
                return replacement
            }
            return self

        case .application(let function, let argument):
            return .application(
                function: function.substituting(name: name, with: replacement),
                argument: argument.substituting(name: name, with: replacement)
            )

        case .abstraction(let param, let type, let body):
            if param == name {
                return self
            }
            if !replacement.freeVariables.contains(param) {
                return .abstraction(
                    param: param,
                    type: type,
                    body: body.substituting(name: name, with: replacement)
                )
            }
            let fresh = Self.freshName(
                avoiding: allVariableNames
                    .union(replacement.allVariableNames)
                    .union([name])
            )
            let renamedBody = body.substituting(name: param, with: .variable(fresh))
            return .abstraction(
                param: fresh,
                type: type,
                body: renamedBody.substituting(name: name, with: replacement)
            )
        }
    }
}

// MARK: - β-reduction to normal form

extension Term {

    /// Reduces this term to its **β-normal form** using **normal-order** evaluation.
    ///
    /// Contracts redexes *(λx:τ. t) u* via *t[x := u]*; parameter types *τ* are preserved
    /// on remaining abstractions. See module documentation for strategy and motivation.
    ///
    /// - Returns: A β-normal form of `self` when one exists.
    public func reduced() -> Term {
        switch self {
        case .variable:
            return self

        case .abstraction(let param, let type, let body):
            return .abstraction(param: param, type: type, body: body.reduced())

        case .application(let function, let argument):
            let reducedFunction = function.reduced()
            if case .abstraction(let param, _, let body) = reducedFunction {
                return body.substituting(name: param, with: argument).reduced()
            }
            return .application(
                function: reducedFunction,
                argument: argument.reduced()
            )
        }
    }
}

// MARK: - Substitution helpers

private extension Term {

    /// Every variable name appearing in this term, whether bound or free.
    private var allVariableNames: Set<String> {
        switch self {
        case .variable(let name):
            return [name]
        case .abstraction(let param, _, let body):
            return body.allVariableNames.union([param])
        case .application(let function, let argument):
            return function.allVariableNames.union(argument.allVariableNames)
        }
    }

    /// Produces a name not present in ``avoiding``, suitable for α-renaming.
    private static func freshName(avoiding used: Set<String>) -> String {
        var index = 0
        while true {
            let candidate = "$v\(index)"
            if !used.contains(candidate) {
                return candidate
            }
            index += 1
        }
    }
}
